### ISSUE TITLE
Post prototype URL on wiki

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/che#14]
Please post the prototype URL on the wiki so we know where and how to access it. Please post any other information that is need on that page. Thanks.

**Comment by WaltRCodes** [comment]
I keep getting a 500 error when trying to save the page. Here is what I wanted to post "The following is the URL to access the prototype instance of Che that is accessible once the following command runs bin/che.sh run -r:54.236.77.133
http://ec2-54-236-77-133.compute-1.amazonaws.com:8080/dashboard/#/"

**Comment by khatchad** [comment]
Save which page?

**Comment by WaltRCodes** [comment]
Nevermind, the page is here: https://github.com/khatchadourian-lab/che/wiki/Prototype-URL

**Comment by khatchad** [comment]
It doesn't work when I click the link.

**Comment by WaltRCodes** [comment]
the wiki or the Che URL? The Che URL doesn't work yet because I haven't set the script yet.

**Comment by khatchad** [comment]
Che URL. Ah ok.

**Comment by khatchad** [comment]
@WaltRCodes We good here?

**Comment by WaltRCodes** [comment]
Yes, the page has the correct url
