### ISSUE TITLE
Source Code Download

### ISSUE THREAD

**Issue by WaltRCodes** [ponder-lab/che#7]
As it stands now, the code for projects is stored on the server. While we can have students just copy their code for Assignments, we may want to look into a way to fully download their projects.

**Comment by khatchad** [comment]
This should be a deal breaker. Students _must_ be able to download _files_. Projects could be a different issue.

On Sun, Apr 10, 2016 at 10:10:17AM -0700, Walter Rada wrote:

> As it stands now, the code for projects is stored on the server. While we can
> have students just copy their code for Assignments, we may want to look into a
> way to fully download their projects.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*

## 

Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad

**Comment by khatchad** [comment]
Why closed?

**Comment by WaltRCodes** [comment]
I closed it because  found out that it does have the ability to download files.

**Comment by khatchad** [comment]
In general, you should leave a comment that justifies the closing of the issue (for example, a commit number, label). In this case, however, I did not see a download feature on codenvy.com, so I would need to see more evidence of this.

**Comment by khatchad** [comment]
Like a screenshot?

**Comment by WaltRCodes** [comment]
Here is one
![download](https://cloud.githubusercontent.com/assets/7140094/14584371/e622587e-0411-11e6-8c03-b4963fc76a1f.PNG)

**Comment by khatchad** [comment]
Looks great, thanks!
